# Docker Compose file for testing
version: "3.8"

services:

  web:
    build:
      context: ..
      dockerfile: Dockerfile
      target: metabrainz-dev
    volumes:
      - ..:/code/metabrainz
    depends_on:
      - db
      - redis

  db:
    image: postgres:12.3
    environment:
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:3.2.1
